trigger:
  - master

pool:
  vmImage: windows-latest

steps:
  - checkout: self
    submodules: true
  - task: PowerShell@2
    displayName: 'Build site'
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)\build.ps1

  - task: AzureFileCopy@2
    inputs:
      SourcePath: '$(Build.SourcesDirectory)\docs'
      additionalArgumentsForBlobCopy: /Y /S /SetContentType:text/html /Pattern:*.html
      azureSubscription: 'AmandaSilver_TeamDemoSub_Connection'
      Destination: 'AzureBlob'
      storage: 'visualstudiokeyboard'
      ContainerName: '$web'