trigger:
  - master

pool:
  vmImage: windows-latest

steps:
  - checkout: self
    submodules: true
  - task: PowerShell@2
    displayName: 'Build site'
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)\build.ps1
  - task: AzureFileCopy@2
    displayName: Deploy html files
    inputs:
      sourcePath: $(Build.DefaultWorkingDirectory)\docs
      additionalArgumentsForBlobCopy: /Y /S /SetContentType:text/html /Pattern:*.html
      azureSubscription: AmandaSilver_TeamDemoSub(7262140c-ccfa-48c9-934d-aab7e37fa804)
      destination: AzureBlob
      storage: visualstudiokeyboard
      containerName: $web 